# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.24", "1.25"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}

      - name: Build
        run: go build -C jj -v ./...

      - name: Test
        run: go test -C jj -v ./...

      - name: Vet
        run: go vet -C jj -v ./...

      - name: Format
        run: '[ ! "$(gofmt -s -l jj)" ]'

      - name: Imports
        run: '[ ! "$(go run golang.org/x/tools/cmd/goimports -l jj)" ]'
