name: License

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go ${{matrix.go-version}}
        uses: actions/setup-go@v5
        with:
          go-version: ${{matrix.go-version}}

      - name: Check
        run: go run github.com/google/addlicense@v1.1.1 -check -s=only jj/**
